/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../../contexts/Customization'

export function RingShape2(props) {
  const { nodes, materials } = useGLTF('/models/rings/Ring2-variations.glb')



  const {
    ringColorShape2,
    diamondColorShape2,
    headerColorShape2,
    selectedDiamondShape2,
    selectedHeaderShape2
  } = useCustomization()

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R2M7001.geometry}
        material={materials['R2M70.003']}
        position={[-0.001, 0.565, 0.002]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        material-color={ringColorShape2.color}
        visible={true}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R2M3.geometry}
        material={materials['R2M30.002']}
        position={[0.001, 1.007, -0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        material-color={diamondColorShape2.color}
        visible={selectedDiamondShape2 == 'Diamond 1'}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R2M3001.geometry}
        material={materials['R2M30.003']}
        position={[0.001, 0.999, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        material-color={diamondColorShape2.color}
        visible={selectedDiamondShape2 == 'Diamond 2'}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R2M6.geometry}
        material={materials['R2M60.002']}
        position={[-0.001, 0.97, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        material-color={headerColorShape2.color}
        visible={selectedHeaderShape2 == "Heading 1"}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R2M6001.geometry}
        material={materials['R2M60.003']}
        position={[-0.001, 0.974, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        material-color={headerColorShape2.color}
        visible={selectedHeaderShape2 == "Heading 2"}
      />
    </group>
  )
}

useGLTF.preload('/models/rings/Ring2-variations.glb')