/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../../contexts/Customization';

export function RingShape1(props) {
    const { nodes, materials } = useGLTF('/models/rings/Ring1-variations.glb')

    const {
        ringColor,
        diamondColor,
        headerColor,
        selectedDiamond,
        selectedHeader
    } = useCustomization();

    // switch(selectedDiamond) {
    //     case 'Diamond 1':
    //       return 'bar';
    //     case 'Diamond 2':
    //       return 'bar';
    //     case 'Diamond 3':
    //       return 'bar';
    //     default:
    //       return 'foo';
    //   }

    //   Gotta do the switch case of retrieving the diamond name and then attribute the visibility for each diamond


    console.log(ringColor)

    return (
        <group {...props} dispose={null} >

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Circle.geometry}
                material={materials['R70.003']}
                position={[0, 0.555, 0.001]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={ringColor.color}

            />

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Header_2.geometry}
                material={materials['R60.003']}
                position={[0, 0.886, 0.002]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={headerColor.color}
                visible={selectedHeader == 'Heading 2'}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Diamond_1.geometry}
                material={materials['R30.002']}
                position={[-0.001, 0.909, -0.001]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={diamondColor.color}
                visible={selectedDiamond == 'Diamond 1'}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Diamond_2.geometry}
                material={materials['R30.003']}
                position={[0.001, 0.918, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={diamondColor.color}
                visible={selectedDiamond == 'Diamond 2'}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Header_1.geometry}
                material={materials['R60.004']}
                position={[-0.001, 0.88, 0.001]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={headerColor.color}
                visible={selectedHeader == 'Heading 1'}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Header_3.geometry}
                material={materials['R70.005']}
                position={[-0.001, 0.883, 0.001]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={headerColor.color}
                visible={selectedHeader == 'Heading 3'}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Diamond_3.geometry}
                material={materials['R60.005']}
                position={[0.001, 0.91, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={50}
                material-color={diamondColor.color}
                visible={selectedDiamond == 'Diamond 3'}
            />

        </group>
    )
}

useGLTF.preload('/models/rings/Ring1-variations.glb')