/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../../contexts/Customization'

export function RingShape3(props) {
  const { nodes, materials } = useGLTF('/models/rings/Ring3-variations.glb')


  const {
    ringColorShape3,
    diamondColorShape3,
    headerColorShape3,
    selectedDiamondShape3,
    selectedHeaderShape3
  } = useCustomization()

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cirlcle.geometry}
        material={materials.R3M50}
        position={[-0.001, 0.579, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={true}
        material-color={ringColorShape3.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Header1.geometry}
        material={materials.R3M40}
        position={[-0.001, 1.112, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={selectedHeaderShape3 == 'Heading 1'}
        material-color={headerColorShape3.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Diamond1.geometry}
        material={materials.R3M10}
        position={[0.001, 1.137, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={selectedDiamondShape3 == 'Diamond 1'}
        material-color = {diamondColorShape3.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Diamond2.geometry}
        material={materials.R3M30}
        position={[0, 1.146, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={selectedDiamondShape3 == 'Diamond 2'}
        material-color = {diamondColorShape3.color}

      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Header2.geometry}
        material={materials.R3M60}
        position={[0, 1.107, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={selectedHeaderShape3 == 'Heading 2'}
        material-color={headerColorShape3.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Diamond3.geometry}
        material={materials['R3M30.001']}
        position={[0, 1.135, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={selectedDiamondShape3 == 'Diamond 3'}
        material-color = {diamondColorShape3.color}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Header3.geometry}
        material={materials.R3M90}
        position={[0, 1.113, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
        visible={selectedHeaderShape3 == 'Heading 3'}
        material-color = {headerColorShape3.color}
      />
    </group>
  )
}

useGLTF.preload('/models/rings/Ring3-variations.glb')