/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cube(props) {
  const { nodes, materials } = useGLTF("/models/Leaves.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leaves.geometry}
        material={materials.Blocks_Pixelart}
      />
    </group>
  );
}

useGLTF.preload("/models/Leaves.gltf");
