/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useRef, useState } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import {
  useGLTF,
  useCursor,
  useTexture,
  Text,
  Decal,
  Environment,
  OrbitControls,
  RenderTexture,
  RandomizedLight,
  PerspectiveCamera,
  AccumulativeShadows
} from '@react-three/drei'


export function Dodo(props) {
    const meshRef = useRef()
    const texture = useTexture('/logo.png')
    const [hovered, hover] = useState(false)
    const [clicked, click] = useState(false)
    useCursor(hovered)
    return (
      <group {...props}>
        <mesh
          ref={meshRef}
          scale={clicked ? 2.25 : 1.75}
          onClick={() => click(!clicked)}
          onPointerOver={() => hover(true)}
          onPointerOut={() => hover(false)}>
          <dodecahedronGeometry args={[0.75]} />
          <meshStandardMaterial color={hovered ? 'hotpink' : 'goldenrod'} />
          <Decal polygonOffsetFactor={-0} position={[0, .2, 0.5]} scale={1} map={texture} />
        </mesh>
      </group>
    )
  }

