/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Island(props) {
  const { nodes, materials } = useGLTF("/models/house.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice.geometry}
        material={materials["Atlas.003"]}
        position={[-10, 0, 0]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center.geometry}
        material={materials["Atlas.018"]}
        position={[-8, 2, 0]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Corner.geometry}
        material={materials["Atlas.026"]}
        position={[-8, 2, -16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_GreyBricks.geometry}
        material={materials["Atlas.036"]}
        position={[-19, 3.67, -12]}
        scale={2.645}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass001.geometry}
        material={materials.Atlas}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass002.geometry}
        material={materials.Atlas}
        position={[0, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass003.geometry}
        material={materials.Atlas}
        position={[0, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass004.geometry}
        material={materials.Atlas}
        position={[0, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass005.geometry}
        material={materials.Atlas}
        position={[0, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass006.geometry}
        material={materials.Atlas}
        position={[0, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass007.geometry}
        material={materials.Atlas}
        position={[0, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass008.geometry}
        material={materials.Atlas}
        position={[0, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass009.geometry}
        material={materials.Atlas}
        position={[0, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass010.geometry}
        material={materials.Atlas}
        position={[0, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass011.geometry}
        material={materials.Atlas}
        position={[2, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass012.geometry}
        material={materials.Atlas}
        position={[2, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass013.geometry}
        material={materials.Atlas}
        position={[2, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass014.geometry}
        material={materials.Atlas}
        position={[2, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass015.geometry}
        material={materials.Atlas}
        position={[2, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass016.geometry}
        material={materials.Atlas}
        position={[2, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass017.geometry}
        material={materials.Atlas}
        position={[2, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass018.geometry}
        material={materials.Atlas}
        position={[2, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass019.geometry}
        material={materials.Atlas}
        position={[2, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass020.geometry}
        material={materials.Atlas}
        position={[2, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass021.geometry}
        material={materials.Atlas}
        position={[4, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass022.geometry}
        material={materials.Atlas}
        position={[4, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass023.geometry}
        material={materials.Atlas}
        position={[4, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass024.geometry}
        material={materials.Atlas}
        position={[4, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass025.geometry}
        material={materials.Atlas}
        position={[4, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass026.geometry}
        material={materials.Atlas}
        position={[4, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass027.geometry}
        material={materials.Atlas}
        position={[4, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass028.geometry}
        material={materials.Atlas}
        position={[4, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass029.geometry}
        material={materials.Atlas}
        position={[4, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass030.geometry}
        material={materials.Atlas}
        position={[4, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass031.geometry}
        material={materials.Atlas}
        position={[6, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass032.geometry}
        material={materials.Atlas}
        position={[6, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass033.geometry}
        material={materials.Atlas}
        position={[6, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass034.geometry}
        material={materials.Atlas}
        position={[6, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass035.geometry}
        material={materials.Atlas}
        position={[6, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass036.geometry}
        material={materials.Atlas}
        position={[6, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass037.geometry}
        material={materials.Atlas}
        position={[6, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass038.geometry}
        material={materials.Atlas}
        position={[6, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass039.geometry}
        material={materials.Atlas}
        position={[6, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass040.geometry}
        material={materials.Atlas}
        position={[6, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass041.geometry}
        material={materials.Atlas}
        position={[8, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass042.geometry}
        material={materials.Atlas}
        position={[8, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass043.geometry}
        material={materials.Atlas}
        position={[8, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass044.geometry}
        material={materials.Atlas}
        position={[8, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass045.geometry}
        material={materials.Atlas}
        position={[8, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass046.geometry}
        material={materials.Atlas}
        position={[8, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass047.geometry}
        material={materials.Atlas}
        position={[8, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass048.geometry}
        material={materials.Atlas}
        position={[8, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass049.geometry}
        material={materials.Atlas}
        position={[8, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass050.geometry}
        material={materials.Atlas}
        position={[8, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass051.geometry}
        material={materials.Atlas}
        position={[10, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass052.geometry}
        material={materials.Atlas}
        position={[10, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass053.geometry}
        material={materials.Atlas}
        position={[10, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass054.geometry}
        material={materials.Atlas}
        position={[10, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass055.geometry}
        material={materials.Atlas}
        position={[10, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass056.geometry}
        material={materials.Atlas}
        position={[10, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass057.geometry}
        material={materials.Atlas}
        position={[10, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass058.geometry}
        material={materials.Atlas}
        position={[10, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass059.geometry}
        material={materials.Atlas}
        position={[10, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass060.geometry}
        material={materials.Atlas}
        position={[10, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass061.geometry}
        material={materials.Atlas}
        position={[12, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass062.geometry}
        material={materials.Atlas}
        position={[12, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass063.geometry}
        material={materials.Atlas}
        position={[12, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass064.geometry}
        material={materials.Atlas}
        position={[12, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass065.geometry}
        material={materials.Atlas}
        position={[12, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass066.geometry}
        material={materials.Atlas}
        position={[12, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass067.geometry}
        material={materials.Atlas}
        position={[12, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass068.geometry}
        material={materials.Atlas}
        position={[12, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass069.geometry}
        material={materials.Atlas}
        position={[12, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass070.geometry}
        material={materials.Atlas}
        position={[12, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass071.geometry}
        material={materials.Atlas}
        position={[14, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass072.geometry}
        material={materials.Atlas}
        position={[14, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass073.geometry}
        material={materials.Atlas}
        position={[14, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass074.geometry}
        material={materials.Atlas}
        position={[14, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass075.geometry}
        material={materials.Atlas}
        position={[14, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass076.geometry}
        material={materials.Atlas}
        position={[14, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass077.geometry}
        material={materials.Atlas}
        position={[14, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass078.geometry}
        material={materials.Atlas}
        position={[14, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass079.geometry}
        material={materials.Atlas}
        position={[14, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass080.geometry}
        material={materials.Atlas}
        position={[14, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass081.geometry}
        material={materials.Atlas}
        position={[16, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass082.geometry}
        material={materials.Atlas}
        position={[16, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass083.geometry}
        material={materials.Atlas}
        position={[16, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass084.geometry}
        material={materials.Atlas}
        position={[16, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass085.geometry}
        material={materials.Atlas}
        position={[16, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass086.geometry}
        material={materials.Atlas}
        position={[16, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass087.geometry}
        material={materials.Atlas}
        position={[16, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass088.geometry}
        material={materials.Atlas}
        position={[16, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass089.geometry}
        material={materials.Atlas}
        position={[16, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass090.geometry}
        material={materials.Atlas}
        position={[16, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass091.geometry}
        material={materials.Atlas}
        position={[18, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass092.geometry}
        material={materials.Atlas}
        position={[18, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass093.geometry}
        material={materials.Atlas}
        position={[18, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass094.geometry}
        material={materials.Atlas}
        position={[18, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass095.geometry}
        material={materials.Atlas}
        position={[18, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass096.geometry}
        material={materials.Atlas}
        position={[18, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass097.geometry}
        material={materials.Atlas}
        position={[18, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass098.geometry}
        material={materials.Atlas}
        position={[18, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass099.geometry}
        material={materials.Atlas}
        position={[18, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass100.geometry}
        material={materials.Atlas}
        position={[18, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass101.geometry}
        material={materials["Atlas.001"]}
        position={[18, 1, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass102.geometry}
        material={materials["Atlas.001"]}
        position={[18, 1, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass103.geometry}
        material={materials["Atlas.001"]}
        position={[18, 1, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass104.geometry}
        material={materials["Atlas.001"]}
        position={[16, 1, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass105.geometry}
        material={materials["Atlas.001"]}
        position={[16, 2, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass106.geometry}
        material={materials["Atlas.001"]}
        position={[16, 2, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass107.geometry}
        material={materials["Atlas.001"]}
        position={[14, 1, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass108.geometry}
        material={materials["Atlas.001"]}
        position={[14, 2, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass109.geometry}
        material={materials["Atlas.001"]}
        position={[12, 1, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass110.geometry}
        material={materials["Atlas.001"]}
        position={[12, 2, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass111.geometry}
        material={materials["Atlas.001"]}
        position={[10, 1, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass113.geometry}
        material={materials["Atlas.001"]}
        position={[8, 1, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass114.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass115.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass116.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass117.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass118.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass119.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass120.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass121.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass122.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass123.geometry}
        material={materials["Atlas.002"]}
        position={[-2, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass124.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass125.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass126.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass127.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass128.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass129.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass130.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass131.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass132.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass133.geometry}
        material={materials["Atlas.002"]}
        position={[-4, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass134.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass135.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass136.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass137.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass138.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass139.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass140.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass141.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass142.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass143.geometry}
        material={materials["Atlas.002"]}
        position={[-6, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass144.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass145.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass146.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass147.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass148.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass149.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass150.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass151.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass152.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass153.geometry}
        material={materials["Atlas.002"]}
        position={[-8, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice001.geometry}
        material={materials["Atlas.004"]}
        position={[-10, 0, -2]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice002.geometry}
        material={materials["Atlas.005"]}
        position={[-10, 0, -6]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice003.geometry}
        material={materials["Atlas.006"]}
        position={[-10, 0, -4]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice004.geometry}
        material={materials["Atlas.007"]}
        position={[-12, 0, -4]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice005.geometry}
        material={materials["Atlas.008"]}
        position={[-12, 0, -6]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice006.geometry}
        material={materials["Atlas.009"]}
        position={[-12, 0, -2]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Ice007.geometry}
        material={materials["Atlas.010"]}
        position={[-12, 0, 0]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass112.geometry}
        material={materials["Atlas.011"]}
        position={[-12, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass154.geometry}
        material={materials["Atlas.011"]}
        position={[-12, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass155.geometry}
        material={materials["Atlas.011"]}
        position={[-12, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass156.geometry}
        material={materials["Atlas.011"]}
        position={[-12, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass157.geometry}
        material={materials["Atlas.011"]}
        position={[-12, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass158.geometry}
        material={materials["Atlas.011"]}
        position={[-12, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass159.geometry}
        material={materials["Atlas.011"]}
        position={[-10, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass160.geometry}
        material={materials["Atlas.011"]}
        position={[-10, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass161.geometry}
        material={materials["Atlas.011"]}
        position={[-10, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass162.geometry}
        material={materials["Atlas.011"]}
        position={[-10, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass163.geometry}
        material={materials["Atlas.011"]}
        position={[-10, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass164.geometry}
        material={materials["Atlas.011"]}
        position={[-10, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass165.geometry}
        material={materials["Atlas.012"]}
        position={[-10, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass166.geometry}
        material={materials["Atlas.012"]}
        position={[-10, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass167.geometry}
        material={materials["Atlas.012"]}
        position={[-10, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass168.geometry}
        material={materials["Atlas.012"]}
        position={[-12, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass169.geometry}
        material={materials["Atlas.012"]}
        position={[-12, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass170.geometry}
        material={materials["Atlas.013"]}
        position={[-8, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass171.geometry}
        material={materials["Atlas.013"]}
        position={[-8, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass172.geometry}
        material={materials["Atlas.013"]}
        position={[-8, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass173.geometry}
        material={materials["Atlas.013"]}
        position={[-6, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass174.geometry}
        material={materials["Atlas.013"]}
        position={[-6, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass175.geometry}
        material={materials["Atlas.013"]}
        position={[-6, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass176.geometry}
        material={materials["Atlas.013"]}
        position={[-4, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass177.geometry}
        material={materials["Atlas.013"]}
        position={[-4, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass178.geometry}
        material={materials["Atlas.013"]}
        position={[-4, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass179.geometry}
        material={materials["Atlas.013"]}
        position={[-2, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass180.geometry}
        material={materials["Atlas.013"]}
        position={[-2, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass181.geometry}
        material={materials["Atlas.013"]}
        position={[-2, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass182.geometry}
        material={materials["Atlas.012"]}
        position={[-12, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass183.geometry}
        material={materials["Atlas.014"]}
        position={[18, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass184.geometry}
        material={materials["Atlas.014"]}
        position={[18, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass185.geometry}
        material={materials["Atlas.014"]}
        position={[18, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass186.geometry}
        material={materials["Atlas.014"]}
        position={[16, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass187.geometry}
        material={materials["Atlas.014"]}
        position={[16, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass188.geometry}
        material={materials["Atlas.014"]}
        position={[16, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass189.geometry}
        material={materials["Atlas.014"]}
        position={[14, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass190.geometry}
        material={materials["Atlas.014"]}
        position={[14, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass191.geometry}
        material={materials["Atlas.014"]}
        position={[14, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass192.geometry}
        material={materials["Atlas.014"]}
        position={[12, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass193.geometry}
        material={materials["Atlas.014"]}
        position={[12, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass194.geometry}
        material={materials["Atlas.014"]}
        position={[12, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass195.geometry}
        material={materials["Atlas.014"]}
        position={[10, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass196.geometry}
        material={materials["Atlas.014"]}
        position={[10, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass197.geometry}
        material={materials["Atlas.014"]}
        position={[10, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass198.geometry}
        material={materials["Atlas.014"]}
        position={[8, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass199.geometry}
        material={materials["Atlas.014"]}
        position={[8, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass200.geometry}
        material={materials["Atlas.014"]}
        position={[8, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass201.geometry}
        material={materials["Atlas.014"]}
        position={[6, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass202.geometry}
        material={materials["Atlas.014"]}
        position={[6, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass203.geometry}
        material={materials["Atlas.014"]}
        position={[6, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass204.geometry}
        material={materials["Atlas.014"]}
        position={[4, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass205.geometry}
        material={materials["Atlas.014"]}
        position={[4, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass206.geometry}
        material={materials["Atlas.014"]}
        position={[4, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass207.geometry}
        material={materials["Atlas.014"]}
        position={[2, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass208.geometry}
        material={materials["Atlas.014"]}
        position={[2, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass209.geometry}
        material={materials["Atlas.014"]}
        position={[2, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass210.geometry}
        material={materials["Atlas.014"]}
        position={[0, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass211.geometry}
        material={materials["Atlas.014"]}
        position={[0, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass212.geometry}
        material={materials["Atlas.014"]}
        position={[0, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass213.geometry}
        material={materials["Atlas.015"]}
        position={[-14, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass214.geometry}
        material={materials["Atlas.015"]}
        position={[-14, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass215.geometry}
        material={materials["Atlas.015"]}
        position={[-14, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass216.geometry}
        material={materials["Atlas.015"]}
        position={[-14, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass217.geometry}
        material={materials["Atlas.015"]}
        position={[-14, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass218.geometry}
        material={materials["Atlas.015"]}
        position={[-14, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass219.geometry}
        material={materials["Atlas.015"]}
        position={[-16, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass220.geometry}
        material={materials["Atlas.015"]}
        position={[-16, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass221.geometry}
        material={materials["Atlas.015"]}
        position={[-16, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass222.geometry}
        material={materials["Atlas.015"]}
        position={[-16, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass223.geometry}
        material={materials["Atlas.015"]}
        position={[-16, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass224.geometry}
        material={materials["Atlas.015"]}
        position={[-16, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass225.geometry}
        material={materials["Atlas.016"]}
        position={[-16, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass226.geometry}
        material={materials["Atlas.016"]}
        position={[-16, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass227.geometry}
        material={materials["Atlas.016"]}
        position={[-16, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass228.geometry}
        material={materials["Atlas.016"]}
        position={[-16, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass229.geometry}
        material={materials["Atlas.016"]}
        position={[-16, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass230.geometry}
        material={materials["Atlas.016"]}
        position={[-16, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass231.geometry}
        material={materials["Atlas.016"]}
        position={[-14, 0, 4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass232.geometry}
        material={materials["Atlas.016"]}
        position={[-14, 0, 2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass233.geometry}
        material={materials["Atlas.016"]}
        position={[-14, 0, 0]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass234.geometry}
        material={materials["Atlas.016"]}
        position={[-14, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass235.geometry}
        material={materials["Atlas.016"]}
        position={[-14, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass236.geometry}
        material={materials["Atlas.016"]}
        position={[-14, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass237.geometry}
        material={materials["Atlas.017"]}
        position={[-14, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass238.geometry}
        material={materials["Atlas.017"]}
        position={[-16, 0, 6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center001.geometry}
        material={materials["Atlas.019"]}
        position={[-8, 2, -2]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center002.geometry}
        material={materials["Atlas.020"]}
        position={[-8, 2, -6]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center003.geometry}
        material={materials["Atlas.021"]}
        position={[-8, 2, -4]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center004.geometry}
        material={materials["Atlas.022"]}
        position={[-8, 2, -12]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center005.geometry}
        material={materials["Atlas.023"]}
        position={[-8, 2, -14]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center006.geometry}
        material={materials["Atlas.024"]}
        position={[-8, 2, -10]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center007.geometry}
        material={materials["Atlas.025"]}
        position={[-8, 2, -8]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center008.geometry}
        material={materials["Atlas.027"]}
        position={[-10, 2, -16]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center009.geometry}
        material={materials["Atlas.028"]}
        position={[-12, 2, -16]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fence_Center010.geometry}
        material={materials["Atlas.029"]}
        position={[-14, 2, -16]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass239.geometry}
        material={materials["Atlas.030"]}
        position={[-18, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass240.geometry}
        material={materials["Atlas.030"]}
        position={[-18, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass241.geometry}
        material={materials["Atlas.030"]}
        position={[-18, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass242.geometry}
        material={materials["Atlas.030"]}
        position={[-18, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass243.geometry}
        material={materials["Atlas.030"]}
        position={[-18, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass244.geometry}
        material={materials["Atlas.030"]}
        position={[-18, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass245.geometry}
        material={materials["Atlas.031"]}
        position={[-22, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass246.geometry}
        material={materials["Atlas.031"]}
        position={[-22, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass247.geometry}
        material={materials["Atlas.031"]}
        position={[-22, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass248.geometry}
        material={materials["Atlas.031"]}
        position={[-22, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass249.geometry}
        material={materials["Atlas.031"]}
        position={[-22, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass250.geometry}
        material={materials["Atlas.031"]}
        position={[-22, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass251.geometry}
        material={materials["Atlas.032"]}
        position={[-20, 0, -8]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass252.geometry}
        material={materials["Atlas.032"]}
        position={[-20, 0, -10]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass253.geometry}
        material={materials["Atlas.032"]}
        position={[-20, 0, -12]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass254.geometry}
        material={materials["Atlas.032"]}
        position={[-20, 0, -14]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass255.geometry}
        material={materials["Atlas.032"]}
        position={[-20, 0, -16]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass256.geometry}
        material={materials["Atlas.032"]}
        position={[-20, 0, -18]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass257.geometry}
        material={materials["Atlas.033"]}
        position={[-20, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass258.geometry}
        material={materials["Atlas.033"]}
        position={[-20, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass259.geometry}
        material={materials["Atlas.033"]}
        position={[-20, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass260.geometry}
        material={materials["Atlas.034"]}
        position={[-22, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass261.geometry}
        material={materials["Atlas.034"]}
        position={[-22, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass262.geometry}
        material={materials["Atlas.034"]}
        position={[-22, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass263.geometry}
        material={materials["Atlas.035"]}
        position={[-18, 0, -6]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass264.geometry}
        material={materials["Atlas.035"]}
        position={[-18, 0, -4]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Block_Grass265.geometry}
        material={materials["Atlas.035"]}
        position={[-18, 0, -2]}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/house.glb");