/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mountains(props) {
  const { nodes, materials } = useGLTF("/models/moutains.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0,0,0]} scale={1.742}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mountain_Group_2001_1.geometry}
            material={materials["Stone.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mountain_Group_2001_2.geometry}
            material={materials["Snow.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mountain_Group_2001_3.geometry}
            material={materials["Dirt.001"]}
          />
        </group>
      </group>
      <group position={[0,0,0]} scale={1.742}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mountain_Group_2002_1.geometry}
            material={materials["Stone.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mountain_Group_2002_2.geometry}
            material={materials["Snow.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mountain_Group_2002_3.geometry}
            material={materials["Dirt.002"]}
          />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mountain_Group_2_1.geometry}
          material={materials["Stone.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mountain_Group_2_2.geometry}
          material={materials.Snow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mountain_Group_2_3.geometry}
          material={materials.Dirt}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/moutains.glb");