/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function NewIsland(props) {
  const { nodes, materials } = useGLTF("/models/new-island.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.659}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Landscape_1.geometry}
          material={materials["terrain.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Landscape_2.geometry}
          material={materials.mountain}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Landscape_3.geometry}
          material={materials["top mountain"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Landscape_plane.geometry}
        material={materials["Material.001"]}
        scale={0.514}
      />
    </group>
  );
}

useGLTF.preload("/models/new-island.glb");
