/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rails(props) {
  const { nodes, materials } = useGLTF("/models/trainRails.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RailwayTrack_Straight_1.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RailwayTrack_Straight_2.geometry}
          material={materials.Wood}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/trainRails.glb");