/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rails(props) {
  const { nodes, materials } = useGLTF("/models/rails.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[6.566, 0, -0.017]} rotation={[0, -1.556, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube551.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube551_1.geometry}
          material={materials["Atlas.008"]}
        />
      </group>
      <group position={[-9.14, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube549.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube549_1.geometry}
          material={materials.Atlas}
        />
      </group>
      <group position={[-7.188, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Atlas.001"]}
        />
      </group>
      <group position={[-3.252, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["Atlas.002"]}
        />
      </group>
      <group position={[-5.204, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["Atlas.003"]}
        />
      </group>
      <group position={[2.623, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials["Atlas.004"]}
        />
      </group>
      <group position={[4.574, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials["Atlas.005"]}
        />
      </group>
      <group position={[0.639, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials["Atlas.006"]}
        />
      </group>
      <group position={[-1.313, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Atlas.007"]}
        />
      </group>
      <group position={[6.58, 0, 1.959]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials["Atlas.009"]}
        />
      </group>
      <group position={[6.579, 0, 3.958]} rotation={[0, 1.566, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials["Atlas.010"]}
        />
      </group>
      <group position={[10.524, 0, 3.963]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["Atlas.011"]}
        />
      </group>
      <group position={[8.573, 0, 3.963]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials["Atlas.012"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/rails.glb");