/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rails(props) {
  const { nodes, materials } = useGLTF("/models/rails.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-9.14, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube549.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube549_1.geometry}
          material={materials.Atlas}
        />
      </group>
     
    </group>
  );
}

useGLTF.preload("/models/rails.glb");