/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RingVariation1(props) {
  const { nodes, materials } = useGLTF('/models/ringVariation1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R7.geometry}
        material={materials['R70.003']}
        position={[-0.156, 0.006, 1.87]}
        rotation={[-1.478, 0, 0]}
        scale={-22.639}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R6.geometry}
        material={materials['R60.003']}
        position={[-0.156, 0.006, 1.87]}
        rotation={[-1.478, 0, 0]}
        scale={-22.639}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.R3.geometry}
        material={materials['R30.002']}
        position={[-0.156, 0.006, 1.87]}
        rotation={[-1.478, 0, 0]}
        scale={-22.639}
      />
    </group>
  )
}

useGLTF.preload('/ringVariation1.glb')