/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useLayoutEffect, useState } from 'react'
import { MeshRefractionMaterial, useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useFrame, useLoader, useThree } from '@react-three/fiber'
import { useControls } from 'leva'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { Bloom } from '@react-three/postprocessing'
import { BlurPass, Resizer, KernelSize, Resolution } from 'postprocessing'
import { RGBELoader } from 'three/examples/jsm/Addons.js'
import { Color } from 'three'
import * as THREE from 'three';

export function RingVariation3(props) {


    const t1 = gsap.timeline()
    const texture = useLoader(RGBELoader, 'https://dl.polyhaven.org/file/ph-assets/HDRIs/hdr/1k/aerodynamics_workshop_1k.hdr')

    // const [diamondColor, setDiamondColor] = useState(new THREE.Color(0x39cffe).convertSRGBToLinear())
    const [diamondColor, setDiamondColor] = useState(new THREE.Color(0x39cffe).convertSRGBToLinear())
    const [diamondLerpValue, setDiamondLerpValue] = useState({ x: 0 })



    // setDiamondColor(new Color(0x39cffe).convertSRGBToLinear())

    const config = {
        bounces: 8,
        aberrationStrength: 0.001,
        ior: 1.5,
        fresnel: .8,
    }

    const diamondObjects = [
        'diamonds',
        'diamonds001',
        'diamonds002',
        'diamonds003',
        'diamonds004',
        'diamonds005',
    ]

    let colorLerpValue = { x: 0 }



    const { nodes, materials } = useGLTF('/models/ringVariation3.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.R7.geometry}
                material={materials.silver}
                position={[0.022, 0.049, 0.01]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={-63.182}
            >


                
            </mesh>


            <mesh
                castShadow
                receiveShadow
                geometry={nodes.R3.geometry}
                material={materials.Material_6}
                position={[0.023, 0.513, 0.012]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={-63.182}
            >
                <MeshRefractionMaterial envMap={texture} {...config} color={diamondColor} toneMapped={false} />

            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.R6.geometry}
                material={materials['gold.001']}
                position={[0.021, 0.464, 0.012]}
                rotation={[-Math.PI / 2, 0, Math.PI]}
                scale={-63.182}
            />
        </group>
    )
}




useGLTF.preload('/models/ringVariation3.glb')