/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Scenetest(props) {
  const { nodes, materials } = useGLTF("/models/scenetest.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DeadTree_3.geometry}
        material={materials["Atlas.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock1.geometry}
        material={materials["Atlas.005"]}
        position={[1.197, 0, -0.982]}
        scale={[0.981, 0.602, 0.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock2.geometry}
        material={materials["Atlas.007"]}
        position={[1.705, 0, -0.648]}
        scale={0.602}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cart.geometry}
        material={materials["Atlas.008"]}
        position={[-1.973, 0, 0]}
        scale={[0.625, 0.564, 0.564]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush.geometry}
        material={materials["Atlas.009"]}
        position={[-1.907, 0.37, -0.047]}
        scale={0.331}
      />
      <group position={[-1.021, -0.089, -1.229]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube432.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube432_1.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube432_2.geometry}
          material={materials["Atlas.011"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_Big.geometry}
        material={materials.Atlas}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_Big001.geometry}
        material={materials["Atlas.001"]}
        position={[0, 0, -1.021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_Big002.geometry}
        material={materials["Atlas.003"]}
        position={[0.892, 0, -1.021]}
        scale={[1, 1.484, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass_Big003.geometry}
        material={materials["Atlas.004"]}
        position={[0.892, 0, -0.124]}
        scale={[1, 1.484, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock1001.geometry}
        material={materials["Atlas.006"]}
        position={[0.928, 0.446, -0.982]}
        scale={[0.627, 0.385, 0.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bush001.geometry}
        material={materials["Atlas.010"]}
        position={[-2.1, 0.403, 0.074]}
        scale={0.311}
      />
    </group>
  );
}

useGLTF.preload("/models/scenetest.glb");