/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TrainFront(props) {
  const { nodes, materials } = useGLTF("/models/fullTrain.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[10.391, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_1.geometry}
            material={materials["Ventilation.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_2.geometry}
            material={materials["Black.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_3.geometry}
            material={materials["Main.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_4.geometry}
            material={materials["Windows.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_5.geometry}
            material={materials["DarkMain.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_6.geometry}
            material={materials["Grey.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon_7.geometry}
            material={materials["DarkGrey.001"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels1001.geometry}
          material={materials["Black.001"]}
          position={[3.785, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels2001.geometry}
          material={materials["Black.001"]}
          position={[2.345, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels3001.geometry}
          material={materials["Black.001"]}
          position={[-2.262, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels4001.geometry}
          material={materials["Black.001"]}
          position={[-3.702, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <group position={[20.289, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wagon_ContainerCoal_1.geometry}
            material={materials.Base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wagon_ContainerCoal_2.geometry}
            material={materials.Container}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wagon_ContainerCoal_3.geometry}
            material={materials.Coal}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels1002.geometry}
          material={materials["Black.002"]}
          position={[3.785, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels2002.geometry}
          material={materials["Black.002"]}
          position={[2.345, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels3002.geometry}
          material={materials["Black.002"]}
          position={[-2.262, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels4002.geometry}
          material={materials["Black.002"]}
          position={[-3.702, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <group position={[29.575, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wagon_ContainerCoal001_1.geometry}
            material={materials["Base.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wagon_ContainerCoal001_2.geometry}
            material={materials["Container.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wagon_ContainerCoal001_3.geometry}
            material={materials["Coal.001"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels1003.geometry}
          material={materials["Black.003"]}
          position={[3.785, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels2003.geometry}
          material={materials["Black.003"]}
          position={[2.345, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels3003.geometry}
          material={materials["Black.003"]}
          position={[-2.262, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels4003.geometry}
          material={materials["Black.003"]}
          position={[-3.702, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <group position={[39.244, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_1.geometry}
            material={materials["Ventilation.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_2.geometry}
            material={materials["Black.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_3.geometry}
            material={materials["Main.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_4.geometry}
            material={materials["Windows.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_5.geometry}
            material={materials["DarkMain.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_6.geometry}
            material={materials["Grey.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CargoTrain_Wagon001_7.geometry}
            material={materials["DarkGrey.002"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels1004.geometry}
          material={materials["Black.004"]}
          position={[3.785, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels2004.geometry}
          material={materials["Black.004"]}
          position={[2.345, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels3004.geometry}
          material={materials["Black.004"]}
          position={[-2.262, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wheels4004.geometry}
          material={materials["Black.004"]}
          position={[-3.702, 0.227, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <group
        position={[0.083, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_2.geometry}
          material={materials.Ventilation}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_3.geometry}
          material={materials["Main.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_4.geometry}
          material={materials.Windows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_5.geometry}
          material={materials.DarkMain}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_6.geometry}
          material={materials.Grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_7.geometry}
          material={materials.DarkGrey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_8.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Train_9.geometry}
          material={materials.Lights}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheels1.geometry}
        material={materials.Black}
        position={[-3.702, 0.227, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheels2.geometry}
        material={materials.Black}
        position={[-2.262, 0.227, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheels3.geometry}
        material={materials.Black}
        position={[2.345, 0.227, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheels4.geometry}
        material={materials.Black}
        position={[3.785, 0.227, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/fullTrain.glb");
