/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tree2(props) {
  const { nodes, materials } = useGLTF("/models/Tree_2.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tree_2.geometry}
        material={materials.Atlas}
      />
    </group>
  );
}

useGLTF.preload("/models/Tree_2.gltf");